import type { RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/Login.vue'),
    meta: { titleKey: 'routes.login', public: true },
  },
  {
    path: '/boss/login',
    name: 'BossLogin',
    component: () => import('@/views/antler/BossLoginPage.vue'),
    meta: { titleKey: 'routes.bossLogin', public: true },
  },
  {
    path: '/',
    component: () => import('@/layouts/DefaultLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      {
        path: '',
        redirect: { name: 'PixelOffice' },
      },
      // ── AntlerOffice 2.0 boss menu ────────────────────────────────────────
      {
        path: 'office',
        name: 'PixelOffice',
        component: () => import('@/views/antler/PixelOfficePage.vue'),
        meta: { titleKey: 'routes.pixelOffice', icon: 'BusinessOutline', gateway: 'openclaw', tier: 'boss', fullBleed: true },
      },
      {
        path: 'home',
        name: 'BossDashboard',
        component: () => import('@/views/antler/BossDashboardPage.vue'),
        meta: { titleKey: 'routes.bossHome', icon: 'GridOutline', gateway: 'openclaw', tier: 'boss' },
      },
      {
        path: 'hire',
        redirect: { name: 'AntlerAgents', query: { tab: 'browse' } },
        meta: { hidden: true },
      },
      {
        path: 'skins',
        name: 'AntlerSkins',
        component: () => import('@/views/antler/SkinsPage.vue'),
        meta: { titleKey: 'routes.antlerSkins', icon: 'ColorPaletteOutline', gateway: 'openclaw', tier: 'boss' },
      },
      {
        path: 'channels',
        name: 'AntlerChannels',
        component: () => import('@/views/antler/AntlerChannelsPage.vue'),
        meta: { titleKey: 'routes.antlerChannels', icon: 'GitNetworkOutline', gateway: 'openclaw', tier: 'boss' },
      },
      {
        path: 'connect',
        redirect: { name: 'AntlerChannels' },
        meta: { hidden: true },
      },
      {
        path: 'integrations',
        name: 'Integrations',
        component: () => import('@/views/antler/IntegrationsPage.vue'),
        meta: { titleKey: 'routes.integrations', icon: 'LinkOutline', gateway: 'openclaw', tier: 'boss' },
      },
      {
        path: 'agents',
        name: 'AntlerAgents',
        component: () => import('@/views/antler/AntlerAgentsPage.vue'),
        meta: { titleKey: 'routes.agents', icon: 'PeopleOutline', gateway: 'openclaw', tier: 'boss' },
      },
      {
        path: 'skills',
        name: 'AntlerSkills',
        component: () => import('@/views/antler/AntlerSkillsPage.vue'),
        meta: { titleKey: 'routes.skills', icon: 'ExtensionPuzzleOutline', gateway: 'openclaw', tier: 'boss' },
      },
      {
        path: 'materials',
        name: 'AntlerMaterials',
        component: () => import('@/views/antler/MaterialsPage.vue'),
        meta: { titleKey: 'routes.materials', icon: 'FolderOpenOutline', gateway: 'openclaw', tier: 'boss' },
      },
      {
        path: 'jobs',
        name: 'AntlerCompleteJob',
        component: () => import('@/views/antler/AntlerCompleteJobPage.vue'),
        meta: { titleKey: 'routes.completeJob', icon: 'CheckmarkDoneOutline', gateway: 'openclaw', tier: 'boss' },
      },
      {
        path: 'schedule',
        name: 'AntlerSchedule',
        component: () => import('@/views/antler/AntlerSchedulePage.vue'),
        meta: { titleKey: 'routes.schedule', icon: 'CalendarOutline', gateway: 'openclaw', tier: 'boss' },
      },
      // ── OpenClaw Admin (advanced) ─────────────────────────────────────────
      {
        path: 'admin',
        name: 'AdminDashboard',
        component: () => import('@/views/Dashboard.vue'),
        meta: { titleKey: 'routes.adminDashboard', icon: 'AnalyticsOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'chat',
        name: 'Chat',
        component: () => import('@/views/chat/ChatPage.vue'),
        meta: { titleKey: 'routes.chat', icon: 'ChatboxEllipsesOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'sessions',
        name: 'Sessions',
        component: () => import('@/views/sessions/SessionsPage.vue'),
        meta: { titleKey: 'routes.sessions', icon: 'ChatbubblesOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'sessions/:key',
        name: 'SessionDetail',
        component: () => import('@/views/sessions/SessionDetailPage.vue'),
        meta: { titleKey: 'routes.sessionDetail', hidden: true },
      },
      {
        path: 'memory',
        name: 'Memory',
        component: () => import('@/views/memory/MemoryPage.vue'),
        meta: { titleKey: 'routes.memory', icon: 'BookOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'cron',
        redirect: { name: 'AntlerSchedule' },
        meta: { hidden: true },
      },
      {
        path: 'cron-admin',
        name: 'Cron',
        component: () => import('@/views/cron/CronPage.vue'),
        meta: { titleKey: 'routes.cronAdmin', icon: 'CalendarOutline', gateway: 'openclaw', tier: 'advanced', hidden: true },
      },
      {
        path: 'models',
        name: 'Models',
        component: () => import('@/views/models/ModelsPage.vue'),
        meta: { titleKey: 'routes.models', icon: 'SparklesOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'config',
        redirect: { name: 'Models' },
        meta: { hidden: true },
      },
      {
        path: 'skills-admin',
        name: 'Skills',
        component: () => import('@/views/skills/SkillsPage.vue'),
        meta: { titleKey: 'routes.skillsAdmin', icon: 'ExtensionPuzzleOutline', gateway: 'openclaw', tier: 'advanced', hidden: true },
      },
      {
        path: 'tools',
        redirect: { name: 'AntlerSkills' },
        meta: { hidden: true },
      },
      {
        path: 'system',
        name: 'System',
        component: () => import('@/views/system/SystemPage.vue'),
        meta: { titleKey: 'routes.system', icon: 'PulseOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'terminal',
        name: 'Terminal',
        component: () => import('@/views/terminal/TerminalPage.vue'),
        meta: { titleKey: 'routes.terminal', icon: 'TerminalOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'remote-desktop',
        name: 'RemoteDesktop',
        component: () => import('@/views/remote-desktop/RemoteDesktopPage.vue'),
        meta: { titleKey: 'routes.remoteDesktop', icon: 'DesktopOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'files',
        name: 'Files',
        component: () => import('@/views/files/FilesPage.vue'),
        meta: { titleKey: 'routes.files', icon: 'FolderOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'agents-admin',
        name: 'OpenClawAgents',
        component: () => import('@/views/agents/AgentsPage.vue'),
        meta: { titleKey: 'routes.openClawAgents', icon: 'PeopleOutline', gateway: 'openclaw', tier: 'advanced', hidden: true },
      },
      {
        path: 'workshop',
        name: 'Workshop',
        component: () => import('@/views/office/OfficePage.vue'),
        meta: { titleKey: 'routes.workshop', icon: 'ConstructOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'myworld',
        redirect: { name: 'PixelOffice' },
        meta: { hidden: true },
      },
      {
        path: 'backup',
        name: 'Backup',
        component: () => import('@/views/backup/BackupPage.vue'),
        meta: { titleKey: 'routes.backup', icon: 'ArchiveOutline', gateway: 'openclaw', tier: 'advanced' },
      },
      {
        path: 'monitor',
        name: 'Monitor',
        component: () => import('@/views/monitor/MonitorPage.vue'),
        meta: { titleKey: 'routes.monitor', icon: 'PulseOutline', hidden: true },
      },
      {
        path: 'hermes',
        name: 'HermesDashboard',
        component: () => import('@/views/hermes/HermesDashboard.vue'),
        meta: { titleKey: 'routes.hermesDashboard', icon: 'GridOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/chat',
        name: 'HermesChat',
        component: () => import('@/views/hermes/HermesChatPage.vue'),
        meta: { titleKey: 'routes.hermesChat', icon: 'ChatboxEllipsesOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/sessions',
        name: 'HermesSessions',
        component: () => import('@/views/hermes/HermesSessionsPage.vue'),
        meta: { titleKey: 'routes.hermesSessions', icon: 'ChatbubblesOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/models',
        name: 'HermesModels',
        component: () => import('@/views/hermes/HermesModelsPage.vue'),
        meta: { titleKey: 'routes.hermesModels', icon: 'SparklesOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/channels',
        name: 'HermesChannels',
        component: () => import('@/views/hermes/HermesChannelsPage.vue'),
        meta: { titleKey: 'routes.hermesChannels', icon: 'GitNetworkOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/skills',
        name: 'HermesSkills',
        component: () => import('@/views/hermes/HermesSkillsPage.vue'),
        meta: { titleKey: 'routes.hermesSkills', icon: 'ExtensionPuzzleOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/cron',
        name: 'HermesCron',
        component: () => import('@/views/hermes/HermesCronPage.vue'),
        meta: { titleKey: 'routes.hermesCron', icon: 'CalendarOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/memory',
        name: 'HermesMemory',
        component: () => import('@/views/hermes/HermesMemoryPage.vue'),
        meta: { titleKey: 'routes.hermesMemory', icon: 'BookOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/cli',
        name: 'HermesCli',
        component: () => import('@/views/hermes/HermesCliPage.vue'),
        meta: { titleKey: 'routes.hermesCli', icon: 'CodeSlashOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/terminal',
        name: 'HermesTerminal',
        component: () => import('@/views/hermes/HermesTerminalPage.vue'),
        meta: { titleKey: 'routes.hermesTerminal', icon: 'TerminalOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/remote-desktop',
        name: 'HermesRemoteDesktop',
        component: () => import('@/views/hermes/HermesRemoteDesktopPage.vue'),
        meta: { titleKey: 'routes.hermesRemoteDesktop', icon: 'DesktopOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/files',
        name: 'HermesFiles',
        component: () => import('@/views/hermes/HermesFilesPage.vue'),
        meta: { titleKey: 'routes.hermesFiles', icon: 'FolderOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'hermes/system',
        name: 'HermesSystem',
        component: () => import('@/views/hermes/HermesSystemPage.vue'),
        meta: { titleKey: 'routes.hermesSystem', icon: 'SettingsOutline', gateway: 'hermes', tier: 'advanced' },
      },
      {
        path: 'settings',
        name: 'Settings',
        component: () => import('@/views/settings/SettingsPage.vue'),
        meta: { titleKey: 'routes.settings', icon: 'CogOutline', gateway: 'openclaw', tier: 'advanced' },
      },
    ],
  },
]
